In [3]:
# %pip install pandas
import pandas as pd
import numpy as np

In [4]:
ARQUIVO = r'C:\Users\lucas.emoura\Documents\PastaLucas\aula01_UC2\aula02\03.BaseDPEvolucaoMensalCisp.csv'
df = pd.read_csv(ARQUIVO,
                 sep=';',
                 encoding='IBM860')
df.head(10)

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
0,1,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,0,...,NaN,NaN,21,2,0,0,0,0,578,3
1,4,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,15,6,0,1,0,0,441,3
2,5,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,47,2,1,0,0,0,637,3
3,6,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,6,...,NaN,NaN,26,2,1,0,0,0,473,3
4,7,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,4,...,NaN,NaN,10,1,3,0,0,0,147,3
5,9,1,2003,2003m01,2,1,Rio de Janeiro,3304557,Capital,1,...,NaN,NaN,36,3,0,0,0,0,554,3
6,10,1,2003,2003m01,2,1,Rio de Janeiro,3304557,Capital,1,...,NaN,NaN,40,2,3,0,0,0,593,3
7,12,1,2003,2003m01,19,1,Rio de Janeiro,3304557,Capital,2,...,NaN,NaN,48,3,0,0,0,0,620,3
8,13,1,2003,2003m01,19,1,Rio de Janeiro,3304557,Capital,0,...,NaN,NaN,26,1,0,0,0,0,455,3
9,14,1,2003,2003m01,23,1,Rio de Janeiro,3304557,Capital,0,...,NaN,NaN,43,2,2,0,0,0,636,3

In [5]:
# agregar por município -> analisar roubo de veículo

df_roubo_munic = df [[
    'munic', 'roubo_veiculo'
]]

# agrupar
df_roubo_munic_agg = (
    df_roubo_munic.groupby('munic')
    .sum()
    .reset_index()
    .sort_values(by='roubo_veiculo', ascending=False)
)
df_roubo_munic_agg

                   munic  roubo_veiculo
68        Rio de Janeiro         372584
23       Duque de Caxias          62574
78           Sπo Gonτalo          52539
50           Nova Iguaτu          40235
81    Sπo Joπo de Meriti          30151
..                   ...            ...
66        Rio das Flores              8
58           Porci·ncula              7
46  Natividade;Varre-Sai              6
45              Miracema              6
35        Laje do MuriaΘ              2

[90 rows x 2 columns]

In [ ]:
roubo_array = np.array(df_roubo_munic_agg['roubo_veiculo'])

media = np.mean(roubo_array)
mediana = np.mean(roubo_array)
diff_media_mediana = media - mediana
div_media_mediana = media/mediana

desvio = np.std(roubo_array)
cv = desvio/media

q1 = np.percentile(roubo_array, 25)
q3 = np.percentile(roubo_array, 75)
iqr = q3 - q1

max = np.max(roubo_array)
min = np.min(roubo_array)
amplitude = max - min

In [7]:
assimetria = df['roubo_veiculo'].skew()
curtose = df['roubo_veiculo'].kurtosis()

print(f'Assimetria: {assimetria:.4f}')
print(f'Curtose: {curtose:.4f}')

Assimetria: 2.8412
Curtose: 10.9725

In [ ]:
#%pip install matplotlib

import matplotlib.pyplot as plt

In [ ]:
plt.hist(df['roubo_veiculo'], bins=50)
plt.show()

In [11]:
assimetria = df_roubo_munic_agg['roubo_veiculo'].skew()
kurt = df_roubo_munic_agg['roubo_veiculo'].kurtosis()

print(f'Assimetria por municipio: {assimetria:.4f}')
print(f'Curtose por municipio: {kurt:.4f}')

Assimetria por municipio: 8.6170
Curtose por municipio: 78.2164